using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using Model;
using Sensors.Services;
using Sensors.Utils;

namespace Sensors.Controllers
{
    [Route("[controller]")]
    public class SensorsController : Controller
    {
        private readonly IPublishEndpoint _publishEndpoint;
        private readonly ISensorService _sensorService;

        public SensorsController(IPublishEndpoint publishEndpoint, ISensorService sensorService
        )
        {
            _publishEndpoint = publishEndpoint;
            _sensorService = sensorService;
        }

        /// <summary>
        /// Get a List of all available sensors.
        /// </summary>
        /// <returns>List of sensors</returns>
        [HttpGet("")]
        public IEnumerable<ISensor> GetSensors()
        {
            foreach (var sensor in _sensorService.GetSensors())
            {
                Console.WriteLine(sensor);
            }

            return _sensorService.GetSensors();
        }

        /// <summary>
        /// Get a sensor with given id.
        /// </summary>
        /// <returns>Sensor with a given id</returns>
        [HttpGet("{id:int}")]
        public ISensor GetSensor(int id)
        {
            return _sensorService.GetSensor(id);
        }

        /// <summary>
        /// Generate one SensorData object from a sensor with a given id
        /// </summary>
        /// <param name="id">Given sensor id</param>
        /// <returns>Http status code indicating if single SensorData object was successfully generated</returns>
        [HttpGet("{id:int}/generate-single")]
        public async Task<IActionResult> GenerateSingleDataFromSensor(int id)
        {
            var sensorData = _sensorService.GetSensor(id).GenerateSingleValue();

            try
            {
                await _publishEndpoint.Publish(sensorData);
                await Console.Out.WriteLineAsync(SensorUtils.SensorDataToJson(sensorData));
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.StackTrace);
                return BadRequest();
            }

            return Ok();
        }

        /// <summary>
        /// Generate one SensorData object with user-defined value from a sensor with a given id
        /// </summary>
        /// <param name="id">Given sensor id</param>
        /// <param name="value">Value to be generated by the sensor defined by the user</param>
        /// <returns>Http status code indicating if single SensorData object was successfully generated</returns>
        [HttpGet("{id:int}/generate-single/{data-value}")]
        public async Task<IActionResult> GenerateGivenValueFromSensor(int id, double value)
        {
            var sensorData = _sensorService.GetSensor(id).GenerateSingleValue(value);

            try
            {
                await _publishEndpoint.Publish(sensorData);
                await Console.Out.WriteLineAsync(SensorUtils.SensorDataToJson(sensorData));
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.StackTrace);
                return BadRequest();
            }

            return Ok();
        }

        /// <summary>
        /// Generate one SensorData object for every existing sensor
        /// </summary>
        /// <returns>Http status code indicating if all SensorData objects were successfully generated</returns>
        [HttpGet("generate-single")]
        public async Task<IActionResult> GenerateSingleDataFromAllSensors()
        {
            var sensors = _sensorService.GetSensors();
            foreach (var sensor in sensors)
            {
                try
                {
                    var sensorData = sensor.GenerateSingleValue();
                    await _publishEndpoint.Publish(sensorData);
                    await Console.Out.WriteLineAsync(SensorUtils.SensorDataToJson(sensorData));
                }
                catch (Exception ex)
                {
                    await Console.Out.WriteLineAsync(ex.StackTrace);
                    return BadRequest();
                }
            }

            return Ok();
        }

        /// <summary>
        /// Start generating data from all existing sensors.
        /// </summary>
        [HttpGet("runall")]
        public async Task RunAll()
        {
            var token = _sensorService.GetNewTokenSource().Token;

            var tasks = new ConcurrentBag<Task>();
            Task t;

            foreach (var sensor in _sensorService.GetSensors())
            {
                sensor.IsRunning = true;
                t = Task.Run(() => DoSensorWork(sensor), token);
                tasks.Add(t);
            }

            try
            {
                await Task.WhenAll(tasks.ToArray());
            }
            catch (OperationCanceledException e)
            {
                Console.WriteLine(e);
            }
        }

        /// <summary>
        /// Function for data generating from a single sensor.
        /// </summary>
        /// <param name="sensor">Sensor generating the data.</param>
        private async void DoSensorWork(ISensor sensor)
        {
            while (true)
            {
                var token = _sensorService.GetTokenSource().Token;
                try
                {
                    await GenerateSingleDataFromSensor(sensor.Id);
                    Thread.Sleep(sensor.Interval);
                }
                catch (OperationCanceledException e)
                {
                    await Console.Out.WriteLineAsync(e.StackTrace);
                    return;
                }
                if (token.IsCancellationRequested)
                {
                    return;
                }
            }
        }
        
        /// <summary>
        /// Stop generating data from all existing sensors.
        /// </summary>
        [HttpGet("stopall")]
        public void StopAll()
        {
            _sensorService.GetTokenSource().Cancel();
            Console.WriteLine("\nTask cancellation requested.");
            _sensorService.GetTokenSource().Dispose();
            foreach (var sensor in _sensorService.GetSensors())
            {
                sensor.IsRunning = false;
            }
        }

        /// <summary>
        /// Sets selected sensor's data generation interval 
        /// </summary>
        /// <param name="id">Sensor id</param>
        /// <param name="interval">New value of sensor's interval</param>
        /// <returns></returns>
        [HttpPut("{id:int}/set-interval/{interval:int}")]
        public IActionResult SetSensorInterval(int id, int interval)
        {
            var sensor = _sensorService.GetSensor(id);
            if (sensor == null)
            {
                return NotFound();
            }

            sensor.Interval = interval;
            return Ok();
        }
        
        /// <summary>
        /// Sets selected sensor's data generation interval so it generates user-defined amount of data objects per min
        /// </summary>
        /// <param name="id">Sensor id</param>
        /// <param name="dataPerMin">Amount of data to be generated by this sensor in one minute</param>
        /// <returns></returns>
        [HttpPut("{id:int}/set-datapermin/{dataPerMin:int}")]
        public IActionResult SetSensorDataPerMin(int id, int dataPerMin)
        {
            var sensor = _sensorService.GetSensor(id);
            if (sensor == null)
            {
                return NotFound();
            }

            sensor.Interval = 60000 / dataPerMin;
            return Ok();
        }
        
        /// <summary>
        /// Sets selected sensor's data generation range so it generates data in range [min, max)
        /// </summary>
        /// <param name="id">Sensor id</param>
        /// <param name="min">New lowest possible value to be generated</param>
        /// <param name="max">New highest possible value to be generated</param>
        /// <returns></returns>
        [HttpPut("{id:int}/set-range/{min:double}:{max:double}")]
        public IActionResult SetSensorRange(int id, double min, double max)
        {
            var sensor = _sensorService.GetSensor(id);
            if (sensor == null)
            {
                return NotFound();
            }

            sensor.MinValue = min;
            sensor.MaxValue = max;
            return Ok();
        }
    }
}