# Get list of all existing sensors
GET http://localhost:160/Sensors

###

# Get info about sensor with id = {id}
GET http://localhost:160/Sensors/{id}

###

# Generate single random data from sensor with id = {id}
GET http://localhost:160/Sensors/{id}/generate-single

###

# Generate single data with value = {value} from sensor with id = {id}
GET http://localhost:160/Sensors/{id}/generate-single/{value}

###

# Generate single random data from all sensors (30 data in total)
GET http://localhost:160/Sensors/generate-single

###

# Start generating data from all sensors
GET http://localhost:160/Sensors/runall

###

# Stop generating data from all sensors
GET http://localhost:160/Sensors/stopall

###

# Set sensor's (with id = {id}) data generation interval to a new value = {interval}
PUT http://localhost:160/Sensors/{id}/set-interval/{interval}

###

# Set sensor's (with id = {id}) data generation rate so it generates {datapermin} new data in one minute
PUT http://localhost:160/Sensors/{id}/set-datapermin/{datapermin}

###

# Set sensor's (with id = {id}) data generation range of values so it generates values in range [min, max)
PUT http://localhost:160/Sensors/{id}/set-range/{min}:{max}